### ISSUE TITLE
Import SDDF for France rounds 1:3

### ISSUE THREAD

**Issue by djhurio** [ropensci/essurvey#45]
## Expected Behavior
SDDF data for France rounds 1:3 should be imported with `haven`.

## Current Behavior
I am receiving a warning that fallback to `foreign` has happened.

## Steps to Reproduce (for bugs)
Input:
```
import_sddf_country(country = "France", rounds = 1:3)
```
Output:
```
Warning messages:
1: Round 1 for France was read with the `foreign` package rather than with  the `haven` package for compatibility reasons.
 Please report any issues at https://github.com/ropensci/essurvey/issues
```

## Your Environment
```
─ Session info ───────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.1 (2020-06-06)
 os       Linux Mint 19.3             
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  lv_LV.UTF-8                 
 ctype    lv_LV.UTF-8                 
 tz       Europe/Riga                 
 date     2020-06-17     
```

**Comment by cimentadaj** [comment]
Yep, this is expected. This is due to `haven` having difficulties with encodings and so on. That's why we initially included the `foreign` fall back. Perhaps we should add an encoding argument to all `import_*` functions that redirects to the actual haven call and users can experiment which encoding to use.
